# Configuration file for setting up your sitemap.xml

# mark these resources into sitemap.xml, otherwise ignore them   
PERMISSIBLE_FILES pdf,ppt,pptx,png,jpg,jpeg,svg   

# include rss/atom feed in sitemap.xml, 1 for yes 
INCLUDE_FEED 0

# handles broken urls  
OUTPUT sitemap.xml

